### ISSUE TITLE
Missing tag for 1.3.5 release

### ISSUE THREAD

**Issue by mgorny** [sumerc/yappi#102]
Please push a tag for the 1.3.5 release, so that we can update Gentoo packages.

**Comment by fabaff** [comment]
The same applies for Nixpkgs. Thanks.

**Comment by sumerc** [comment]
Done. I am still doing releases manually, which I should not but no time for CD integration :(

I am also adding this to my release script for to prevent happening again.

Thanks for the heads up!

**Comment by mgorny** [comment]
Thanks!
