### ISSUE TITLE
Version 1.0 is in pypi but latest in master is 0.99

### ISSUE THREAD

**Issue by amoralej** [sumerc/yappi#11]
Latest version in pypi is 1.0 but latest version in setup.py in master is 0.99.

This is inconsistent and makes difficult to track what is actually in pypi and should be fixed. BTW, where is the tarball in pypi coming from?

**Comment by sumerc** [comment]
Fixed. Version change is done locally just before uploading to pypi, forgot to merge back. Now it is done.
