### ISSUE TITLE
pypi doesn't seem to detect readme format

### ISSUE THREAD

**Issue by dimaqq** [sumerc/yappi#12]
https://pypi.org/project/yappi/

There's some trick to pass content type along with `long_description` through `setup.py` to fix that.

**Comment by dimaqq** [comment]
Looks like it's been added in https://github.com/sumerc/yappi/commit/8e36cf68703260079e6cc3715e53d2ee69c0f82a#diff-2eeaed663bd0d25b7e608891384b7298 already, I wonder why it's still weird on pypi...

**Comment by dimaqq** [comment]
Perhaps `long_description_content_type` is read from wheel (egg info dir), but not sdist?

**Comment by sumerc** [comment]
@alioguzhan  do you have any idea on why this might happen?

**Comment by alioguzhan** [comment]
It might be related to the versions of `wheel` and/or `setup tools` and/or `twine`. Next time, can you please upgrade those tools to the latest version and then release a new version?

My package has the almost same `setup.py` content and it is rendering properly:

https://pypi.org/project/ekler/

**Comment by sumerc** [comment]
This is fixed in latest version.
