### ISSUE TITLE
New 3.11 compatible release?

### ISSUE THREAD

**Issue by kanavin** [sumerc/yappi#122]
Python 3.11 is scheduled for release in 4 days, so perhaps a new version should be tagged and released?
https://peps.python.org/pep-0664/

**Comment by sumerc** [comment]
I was waiting on https://github.com/sumerc/yappi/issues/117. 

Will start on this ASAP. Wait for a release soon.

**Comment by sumerc** [comment]
`1.4.0` that supports `3.11` is released.

**Comment by kanavin** [comment]
Thanks!
