### ISSUE TITLE
No source distribution published for v1.6.9

### ISSUE THREAD

**Issue by markgras** [sumerc/yappi#183]
Thanks for the great project! `yappi` v1.6.9 was published ~8 hours ago. However, I noticed that no source distribution was published to PyPI for this version. [Here](https://pypi.org/project/yappi/1.6.9/#files)'s a link to the relevant PyPI artifacts. Looking at the [GitHub Actions run](https://github.com/sumerc/yappi/actions/runs/11722339333) for this release, it seems that the built sdist was not uploaded because it was filtered out by the `dist-*` pattern. Could you please publish this missing artifact? I use `yappi` on aarch64 Linux, and there is currently neither a v1.6.9 sdist nor wheel available for use. Thank you! (It would be extra awesome if you started publishing aarch64 manylinux wheels, too!)

**Comment by sumerc** [comment]
Oh!

Thanks for pointing this issue out!

**Comment by sumerc** [comment]
Fixed in latest version `1.6.10`
