### ISSUE TITLE
Bug when installed with pip

### ISSUE THREAD

**Issue by xkcdjerry** [sumerc/yappi#20]
When yappi is installed with pip, it crashes with the following error:
![image](https://user-images.githubusercontent.com/49294431/64856513-b98af780-d654-11e9-9a41-08a9f768fbca.png)

TEXT VERSION:
Collecting yappi
  Using cached https://files.pythonhosted.org/packages/d2/92/7cd637a19fa2a10c0e55a44f8b36bcb83f0e1943ba8f1fb5edb15c819f2e/yappi-1.0.tar.gz
Installing collected packages: yappi
  Running setup.py install for yappi ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\58394\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\58394\\AppData\\Local\\Temp\\pip-install-zsdo72o2\\yappi\\setup.py'"'"'; __file__='"'"'C:\\Users\\58394\\AppData\\Local\\Temp\\pip-install-zsdo72o2\\yappi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\58394\AppData\Local\Temp\pip-record-1uijfgsm\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\58394\AppData\Local\Temp\pip-install-zsdo72o2\yappi\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying yappi.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_yappi' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\58394\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\58394\\AppData\\Local\\Temp\\pip-install-zsdo72o2\\yappi\\setup.py'"'"'; __file__='"'"'C:\\Users\\58394\\AppData\\Local\\Temp\\pip-install-zsdo72o2\\yappi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\58394\AppData\Local\Temp\pip-record-1uijfgsm\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by alioguzhan** [comment]
I think this is a requirement for `python 3`. See this response on StackOverflow: 

> https://stackoverflow.com/a/40888720/1510671

Also this:

> https://www.scivision.dev/python-windows-visual-c-14-required/

Maybe we should add this notice to the README file? @sumerc

**Comment by xkcdjerry** [comment]
Or maybe you can add it to the wheel?

**Comment by xkcdjerry** [comment]
> You need to install a newer version of `VS C++` with `build-tools`. I think this is a requirement for `python 3`. See this response on StackOverflow:
> 
> > https://stackoverflow.com/a/40888720/1510671
> 
> Also this:
> 
> > https://www.scivision.dev/python-windows-visual-c-14-required/
> 
> Maybe we should add this notice to the README file? @sumerc

The link in the pip is broken, can you include it in the wheel?Thank you!

**Comment by alioguzhan** [comment]
Hey, I am not sure if it is possible the include a Visual Studio related package to the python wheel.

Did you try to install offline `build-tools` from [here](https://aka.ms/vs/16/release/vs_buildtools.exe) and try again?

**Comment by sumerc** [comment]
This issue is related with installation of build-tools. We have an open issue for distributiong Wheels, so closing this one.
