### ISSUE TITLE
Internal Error 15

### ISSUE THREAD

**Issue by divi255** [sumerc/yappi#32]
Good day,

I'm author of [pptop](https://pptop.io/), which has a plugin for yappi profiler. After updating to 1.2.1, Yappi prints a lot of "Internal Error 15" messages when working. I believe the issue is because pptop plugin starts yappi from the own thread, however everything seems to work fine except this message.

p.s. it would be also nice to have an ability obtaining data fields from get_func_stats() by keywords, as I see some of their indexes are changed from version to version.

**Comment by sumerc** [comment]
Hi, 

>I'm author of pptop, which has a plugin for yappi profiler. After updating to 1.2.1, Yappi prints a lot of "Internal Error 15" messages when working. I believe the issue is because pptop plugin starts yappi from the own thread, however everything seems to work fine except this message.

Yes. This error is more an assertion than an error. I introduced it recently to find issues like yours. I will be looking at how pptop is doing something different to trigger that issue. There should not be much effect for this except for some functions(especially some initial threading library ones) might report more time than they ought to take, but the effect will be very minimal. (This is not a new issue BTW, it is there for years I just put an assertion)

>p.s. it would be also nice to have an ability obtaining data fields from get_func_stats() by keywords, as I see some of their indexes are changed from version to version.

Please correct me but is below not working for you?
```python
stats = yappi.get_func_stats()
for stat in stats:
    print(stat.name, stat.ttot, .....etc.)
```
YFuncStats is a list of YFuncStat object. You can see the attributes you can access [here](https://github.com/sumerc/yappi/blob/master/doc/api.md#yfuncstat).

**Comment by sumerc** [comment]
BTW: Is this always reproducible or randomly happens?

**Comment by divi255** [comment]
>for stat in stats:
>    print(stat.name, stat.ttot, .....etc.)

this works  file, thank you. missed it

**Comment by divi255** [comment]
Internal Error 15 happens always, I can't find a case when it doesn't. Let me explain the full scheme how it works:

 - new thread is started inside inspected process via gdb
 - injected server works in a single thread, nothing new is being spawned
 - it receives plugin code via UNIX socket (e.g. import yappi; yappi.start()) and executes it with exec()

**Comment by sumerc** [comment]
Yes. I reproduced the issue when yappi started from a different thread as you suggested. Fix is coming. Stay tuned!

**Comment by sumerc** [comment]
I have released a new version 1.2.3 for this + other issues. Could you please confirm the issue is resolved on your end, too?

**Comment by divi255** [comment]
yes, it's resolved. thank you!

**Comment by sumerc** [comment]
Nice. Thank you, too!
