### ISSUE TITLE
Current release 1.3.0 doesn't support python 3.10

### ISSUE THREAD

**Issue by amoralej** [sumerc/yappi#69]
Python 3.10 will be included in Fedora 35. To make that update smoother, we're building Fedora packages with early pre-releases of Python 3.10 and yappi 1.3.0 is failing to build.

https://bugzilla.redhat.com/show_bug.cgi?id=1899557

I see some patches in master branch to support python 3.10 but it's not included in any release. May you create a new release which includes the required patches?

**Comment by sumerc** [comment]
Releasing a new version ASAP.

**Comment by amoralej** [comment]
> Releasing a new version ASAP.

Thanks!

**Comment by sumerc** [comment]
Done: https://pypi.org/project/yappi/1.3.1/

Could you pls verify the problem fixed on your side? I will close the issue.

**Comment by amoralej** [comment]
I've updated python-yappi in fedora to 1.3.1 https://koji.fedoraproject.org/koji/taskinfo?taskID=55892816 and tested fine with python 3.10

Thanks! for the quick response

**Comment by sumerc** [comment]
Thanks to you, too!
