### ISSUE TITLE
time.sleep doesn't show up in wall time

### ISSUE THREAD

**Issue by aantn** [sumerc/yappi#74]
Is there a way to show time.sleep() in wall time? In the following example, sleep doesn't show up:

```
import yappi
import time

def foo():
    time.sleep(1)

yappi.set_clock_type("wall")
yappi.start()
foo()
yappi.stop()

yappi.get_func_stats().debug_print()
yappi.get_func_stats().print_all()
```

**Comment by aantn** [comment]
Whoops, my bad. I didn't realize I needed `yappi.start(builtins=True)`
Is there a good reason not to pass builtins=True all the time?

**Comment by sumerc** [comment]
Well my initial thinking was: **performance**. In yappi, the more measurements you make the more overhead you will get. My thinking was: `builtins`(C functions) might not be the first thing people look to profile, at least initially? Right?

**Comment by aantn** [comment]
In my case, I don't want to profile the internals of built-in functions,
rather when looking at user written functions I want to see which line in
that function took the most time and sometimes that line is a built-in in.

This is especially true when optimizing for wall time.
