### ISSUE TITLE
Gevent threadpool tracing hooks for yappi

### ISSUE THREAD

**Issue by sumerc** [sumerc/yappi#75]
Hi @Suhail-MOHD,

Not sure if you have been following, but the issue you opened https://github.com/gevent/gevent/issues/1670 seems to fixed/merged.

Do you have any idea on how we should move forward with this? Any change required on our side, maybe update documentation?

**Comment by Suhail-MOHD** [comment]
Hey @sumerc, 

Thanks for notifying me. We should not need any fixes but we can add a test-case to ensure it works. There is also this piece in the [docs](https://github.com/sumerc/yappi/blob/master/doc/greenlet-profiling.md#limitations-in-gevent-profiling) that needs to be removed/updated. I can pick this up if you like!

**Comment by sumerc** [comment]
Hi @Suhail-MOHD. It would be awesome if you can do it. I will feel more confident :)

**Comment by Suhail-MOHD** [comment]
Sure @sumerc! I can take it up. Please note, I am a bit busy till Jan 15th so I'll start work on it right after that.

**Comment by sumerc** [comment]
Sure. Whenever you like.

Thanks for notifying :)

**Comment by sumerc** [comment]
Closing due to being inactive.
