### ISSUE TITLE
New release to support 3.10

### ISSUE THREAD

**Issue by gaborbernat** [sumerc/yappi#89]
Hello with the release of 3.10 in just a few days would be important to cut (at least a sdist level) release of the main branch, as the current version fails to build/install without https://github.com/sumerc/yappi/pull/66/files

**Comment by sumerc** [comment]
Hello! Thanks for the notification.

**Comment by gaborbernat** [comment]
Are you sure, https://github.com/gaborbernat/yappi-test/runs/3803333119?check_suite_focus=true ?

**Comment by sumerc** [comment]
You are definitely right. 

I remember the frame suspended check but later in beta we added https://github.com/sumerc/yappi/commit/d40bc0e8230dd35e05222f5761e3d7f7a75fd46e.

**Comment by sumerc** [comment]
Done in `1.3.3` version.
