### ISSUE TITLE
Request: Support for per-thread function stats

### ISSUE THREAD

**Issue by nav-agarwal** [sumerc/yappi#9]
Is it possible to get thread stats in pstats format?

**Comment by nav-agarwal** [comment]
I meant can we get per-thread function stats in pstats format(as we get by calling yappi.convert2pstats(yappi.get_func_stats())). Right now, per thread information is limited. 

My code is something like this

```
def start_job():
       yappi.start()
       main_func()         #main thread
       func_pstats = yappi.convert2pstats(yappi.get_func_stats())
       func_pstats.dump_stats(funcfile)
       thstats = yappi.get_thread_stats()

def main_func():
     # do some processing
     # spawns n threads. Each thread processes items from queue pushed by main thread
     # push items to main thread q.put()
     # threads.join()
```

I am looking for detailed pstats of each thread to identlify where most of the time is spent by them.

**Comment by sumerc** [comment]
I believe this has been implemented while ago: after getting func_stats(), you can filter on a specific thread id. `yappi.get_func_stats(filter={"ctx_id":<thread id>, })`

**Comment by sumerc** [comment]
The documentation is incomplete for this and other than that there are other problems, too. No example is given on how to obtain context id of a thread and the reason why we don't use thread_id in the filter. We will look into those but in the mean time you can use set_context_id_callback() function to set/get thread id on the internal context object then use that id to filter on the threads.

**Comment by sumerc** [comment]
I have updated the documentation. https://github.com/sumerc/yappi/blob/master/doc/api.md
You can especially look at the get_func_stats() implementation.

The answer to your question is you can do following:
func_pstats = yappi.convert2pstats(yappi.get_func_stats(filter={'ctx_id': <context id of your thread>}))

To get the context id of a thread:
threads = yappi.get_thread_stats()
Now in threads you can both look at the thread_id,name given by OS whatever you want(I do not know how you identify your thread), and get the associated context id.
